variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - tests

before_script:
    - pwd

conventions:
    stage: lint
    script: ci/conventions.sh

shellcheck:
    stage: lint
    script: ci/shellcheck.sh

ansible-lint:
    stage: lint
    script: ci/ansible-lint.sh
    only:
        - branches

molecule:
    stage: tests
    script: ci/molecule.sh test
    only:
        - branches

molecule debug:
    stage: tests
    script: ci/molecule.sh --debug test --destroy never
    only:
        - branches
    when: manual
