variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - tests
    - cleanup

before_script:
    - pwd

conventions:
    stage: lint
    script: ci/conventions.sh

shellcheck:
    stage: lint
    script: ci/shellcheck.sh

ansible-lint:
    stage: lint
    script: ci/ansible-lint.sh
    only:
        - branches

molecule - test:
    stage: tests
    script: ci/molecule.sh "molecule destroy ; molecule test --destroy never"
    only:
        - branches

molecule - debug:
    stage: tests
    script: ci/molecule.sh "molecule destroy ; molecule --debug test --destroy never"
    only:
        - branches
    when: manual

molecule - cleanup:
    stage: cleanup
    script: ci/molecule.sh "molecule destroy"
    only:
        - branches
