---
variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - tests
    - cleanup

before_script:
    - pwd

conventions:
    stage: lint
    script: ci/conventions.sh

shellcheck:
    stage: lint
    script: ci/shellcheck.sh

ansible-lint:
    stage: lint
    script: ci/ansible-lint.sh

molecule - test:
    stage: tests
    script: ci/molecule-all.sh

molecule - cleanup:
    stage: cleanup
    script: ci/molecule.sh "molecule destroy --all"
