---
- name: Install auditbeat
  yum:
    name: auditbeat{{ lm_elk_version|default('') }}
    state: installed
  become: true

- name: configure auditbeat
  template:
    src: etc/auditbeat/auditbeat.yml.j2
    dest: /etc/auditbeat/auditbeat.yml
  notify: restart auditbeat
  become: true

- name: Check if auditd is installed
  command: systemctl list-unit-files
  changed_when: false
  register: lm_auditd_check

- block:
    - name: Disable OS auditd
      service:
        name: auditd
        enabled: false
      become: true
      when: ('auditd.service' in lm_auditd_check.stdout)

    # there bug in ansible, it's not working even with "use: service"
    # https://goo.gl/6UnfmE
    - name: Stop OS auditd
      command: service auditd stop
      args:
        warn: false
      notify: restart auditbeat
      register: lm_service_result
      changed_when: ('OK' in lm_service_result.stdout)
      become: true
  when: ('auditd.service' in lm_auditd_check.stdout)

- block:
    - name: Make sure elasticsearch is running
      wait_for:
        host: "{{ lm_elastic_hosts[0] }}"
        port: "{{ lm_es_http_port }}"
        delay: 3
        timeout: 120

    # check that kibana is running before setting up auditbeat
    # it's needed for uploading dashboards to elastic
    - name: Make sure kibana is running
      wait_for:
        host: "{{ lm_kibana_hosts[0] }}"
        port: "{{ lm_kibana_port }}"
        delay: 3
        timeout: 120

    - name: Auditbeat load index templates
      command: "auditbeat setup --template -E output.logstash.enabled=false \
        -E 'output.elasticsearch.hosts=[\"{{ lm_elastic_hosts[0] }}:{{ lm_es_http_port }}\"]'"
      become: true

    - name: Auditbeat load dashboards
      command: "auditbeat setup --dashboards"
      become: true
  # endblock
  when: lm_auditbeat_init

- name: Start auditbeat
  service:
    name: auditbeat
    state: started
    enabled: true
  become: true
