---
- name: install java
  yum:
    name: "java-{{ lm_es_java_version }}"
  become: true

- name: install elasticsearch
  yum:
    name: elasticsearch
  become: true

- name: configure elasticsearch
  template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    backup: true
  notify: restart elasticsearch
  become: true

- name: set jvm options
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: "-{{ jvm_opt.name }}"
    line: "-{{ jvm_opt.value }}"
  with_items: "{{ lm_elasticsearch_jvm_opts }}"
  loop_control:
    loop_var: jvm_opt
  become: true
  notify: restart elasticsearch

- name: Make sure logging dir is present
  file:
    path: "{{ lm_es_logdir }}"
    group: elasticsearch
    owner: elasticsearch
    state: directory
    mode: 0755
  become: true

- name: Make sure data dir is present
  file:
    path: "{{ lm_es_datadir }}"
    group: elasticsearch
    owner: elasticsearch
    state: directory
    mode: 0755
  become: true

- name: start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true
  become: true
