---
- name: Install elastic.co repo key
  rpm_key:
    state: present
    key: "{{ lm_es_repo_gpg_key }}"
  become: true

- name: Install logstash repo
  yum_repository:
    name: "elasticsearch-{{ lm_es_major_version }}.x"
    description: "Elasticsearch repository for {{ lm_es_major_version }}.x packages"
    baseurl: "{{ lm_es_repo_url }}"
    gpgkey: "{{ lm_es_repo_gpg_key }}"
    gpgcheck: yes
  become: true
