---
- name: Install elastic.co repo key
  rpm_key:
    state: present
    key: "{{ lm_es_repo_gpg_key }}"
  become: true

- name: Install Elastic.co repo
  yum_repository:
    name: "elasticsearch-{{ lm_es_major_version }}.x"
    description: "Elasticsearch repository for {{ lm_es_major_version }}.x packages"
    baseurl: "{{ lm_es_repo_url }}"
    gpgkey: "{{ lm_es_repo_gpg_key }}"
    gpgcheck: true
  become: true

- name: Install curator repo
  yum_repository:
    name: curator-5
    description: CentOS/RHEL 7 repository for Elasticsearch Curator 5.x packages
    baseurl: "{{ lm_cur_repo_url }}"
    gpgkey: "{{ lm_cur_repo_gpg_key }}"
    gpgcheck: true
  become: true
