---
- name: Wait until elasticsearch is running
  command: curl --head --silent {{ lm_elastalert_es_host }}:{{ lm_elastalert_es_port }}/elastalert_status
  args:
    warn: false
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 12
  delay: 5
  changed_when: false

- name: Restart elastalert
  systemd:
    name: elastalert
    state: restarted
  become: true
