---
- name: Install filebeat
  yum:
    name: filebeat{{ lm_elk_version|default('') }}
    state: installed
  become: true
  notify: restart filebeat

- name: configure filebeat
  template:
    src: etc/filebeat/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat
  become: true

- name: Start filebeat
  service:
    name: filebeat
    state: started
    enabled: true
  become: true
