---
- name: install kibana
  yum:
    name: kibana{{ lm_elk_version|default('') }}
    state: installed
  become: true
  notify: restart kibana

- name: configure kibana
  template:
    src: etc/kibana/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: restart kibana
  become: true

- name: start kibana
  service:
    name: kibana
    state: started
    enabled: true
  become: true
