---
- name: install java
  yum:
    name: "java-{{ lm_es_java_version }}"
  become: true

- name: install logstash
  yum:
    name: logstash
    state: installed
  notify: restart logstash
  become: true

- name: Copy config files
  copy:
    src: etc/logstash/conf.d/
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  become: true
  tags: logstash-config

- name: Copy grok patterns
  copy:
    src: etc/logstash/patterns/
    dest: /etc/logstash/patterns/
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  become: true
  tags: logstash-config

- name: Copy config templates
  template:
    src: "{{ template }}"
    dest: /etc/logstash/conf.d/{{ template | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - ../templates/etc/logstash/conf.d/*.j2
  loop_control:
    loop_var: template
  notify: restart logstash
  become: true
  tags: logstash-config

- name: start logstash
  service:
    name: logstash
    state: started
    enabled: true
  become: true
