---
- name: install java
  yum:
    name: "java-{{ lm_es_java_version }}"
  become: true

- name: install logstash
  yum:
    name: logstash{{ lm_elk_version|default('') }}
    state: installed
  notify: restart logstash
  become: true

- name: Copy main config file
  copy:
    src: etc/logstash/logstash.yml
    dest: /etc/logstash/logstash.yml
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  become: true
  tags: logstash-config

- name: Copy config files
  copy:
    src: etc/logstash/conf.d/
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  become: true
  tags: logstash-config

- name: Copy grok patterns
  copy:
    src: etc/logstash/patterns/
    dest: /etc/logstash/patterns/
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  become: true
  tags: logstash-config

- name: Copy config templates
  template:
    src: "{{ template }}"
    dest: /etc/logstash/conf.d/{{ template | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - ../templates/etc/logstash/conf.d/*.j2
  loop_control:
    loop_var: template
  notify: restart logstash
  become: true
  tags: logstash-config

- name: Create dir for custom templates
  file:
    path: /etc/logstash/templates
    state: directory
    mode: 0755
  become: true
  tags: logstash-config
  when: lm_logstash_custom_index_template

- name: Copy custom index template
  template:
    src: etc/logstash/templates/logstash-bs.json.j2
    dest: /etc/logstash/templates/logstash-bs.json
  become: true
  notify: restart logstash
  tags: logstash-config
  when: lm_logstash_custom_index_template

- name: start logstash
  service:
    name: logstash
    state: started
    enabled: true
  become: true
