---
- name: Install Elastic.co repository
  include_tasks: elastic_repo.yml

- name: Set version for yum if defined
  set_fact:
    lm_elk_version: "-{{ lm_elk_version }}"
  when: lm_elk_version is defined

- name: Run playbook by role name
  include_tasks: "{{ item }}.yml"
  with_items: "{{ lm_server_roles }}"
  tags:
    - logstash-config
    - elastalert-config

- name: Deploy custom logrotate for system logs
  template:
    src: etc/logrotate.d/syslog.j2
    dest: /etc/logrotate.d/syslog
    owner: root
    group: root
    mode: 0644
  become: true
  when: lm_manage_logrotate_syslog
