---
- name: Make sure rsyslog is installed
  yum:
    name: rsyslog
    state: present
  become: true

- name: Disable td-agent
  service:
    name: td-agent
    state: stopped
    enabled: false
  become: true
  ignore_errors: true

- name: Set forwarding to log collector
  template:
    src: etc/rsyslog.d/log-management.conf.j2
    dest: /etc/rsyslog.d/log-management.conf
  notify: restart rsyslog
  become: true

- name: Listen on all interfaces
  template:
    src: etc/rsyslog.d/listen-remote.conf.j2
    dest: /etc/rsyslog.d/listen-remote.conf
  notify: restart rsyslog
  become: true
  when: lm_rsyslog_listen_enable
