---
- name: restart logstash
  service:
    name: logstash
    state: restarted
  become: true

- name: restart kibana
  service:
    name: kibana
    state: restarted
  become: true

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
  become: true

- name: restart auditbeat
  service:
    name: auditbeat
    state: restarted
  become: true

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  become: true
