---
- name: restart logstash
  service:
    name: logstash
    state: restarted
  become: true

- name: restart kibana
  service:
    name: kibana
    state: restarted
  become: true

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
  become: true

- name: restart auditbeat
  service:
    name: auditbeat
    state: restarted
  become: true

- name: restart filebeat
  service:
    name: filebeat
    state: restarted
  become: true

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: restart elastalert
  include_tasks: elastalert_handler.yml

- name: restart cerebro
  service:
    name: cerebro
    state: restarted
  become: true
