---
- name: check that machine exists
  vmware_guest_find:
    hostname: "{{ platform.vmware_vcenter_address }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: false
    datacenter: "{{ platform.vmware_datacenter }}"
    name: "{{ platform.vmware_hostname }}"
  register: vmware_find
  failed_when: false

- name: machine found
  debug:
    msg: "INFO Machine {{ platform.vmware_hostname }} already exists, no changes"
  when: vmware_find.folders is defined

- name: create the VM (takes few minutes ...)
  vmware_guest:
    hostname: "{{ platform.vmware_vcenter_address }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: false
    esxi_hostname: "{{ platform.esxi_hostname }}"
    datacenter: "{{ platform.vmware_datacenter }}"
    folder: "/{{ platform.vmware_datacenter }}/vm/"
    resource_pool: Resources
    name: "{{ platform.vmware_hostname }}"
    state: poweredon
    disk:
      - size_gb: "{{ platform.disk_size }}"
        type: thin
        datastore: "{{ platform.vmware_datastore }}"
    hardware:
      memory_mb: "{{ platform.memory }}"
      num_cpus: "{{ platform.cpu }}"
    template: "{{ platform.os_template }}"
    networks:
      - name: "{{ platform.vmware_network_name }}"
        type: dhcp
    wait_for_ip_address: true
  register: create_output
  when: vmware_find.folders is not defined
