---
- name: Find VM folder by name
  vmware_guest_find:
    hostname: "{{ platform.vmware_vcenter_address }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: false
    datacenter: "{{ platform.vmware_datacenter }}"
    name: "{{ platform.vmware_hostname }}"
  register: vmware_find
  failed_when: false
  delegate_to: localhost

- name: Machine not found
  debug:
    msg: "Machine {{ platform.vmware_hostname }} not found, nothing to do."
  when: vmware_find.folders is not defined

- name: Poweroff VM {{ platform.vmware_hostname }}
  vmware_guest:
    hostname: "{{ platform.vmware_vcenter_address }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: false
    name: "{{ platform.vmware_hostname }}"
    folder: "/{{ platform.vmware_datacenter }}/"
    state: poweredoff
  when: vmware_find.folders is defined
  delegate_to: localhost

- name: Delete VM {{ platform.vmware_hostname }}
  vmware_guest:
    hostname: "{{ platform.vmware_vcenter_address }}"
    username: "{{ vsphere_username }}"
    password: "{{ vsphere_password }}"
    validate_certs: false
    name: "{{ platform.vmware_hostname }}"
    folder: "/{{ platform.vmware_datacenter }}/"
    state: absent
  when: vmware_find.folders is defined
  delegate_to: localhost
