---
dependency:
  name: galaxy
  options:
    ignore-certs: true
driver:
  name: delegated
  options:
    managed: true
    ansible_connection_options:
      connection: ssh
      ansible_ssh_common_args: '-F /tmp/ssh_config'
lint:
  name: yamllint
platforms:
  - name: ansible-roletest-log-management
    vmware_hostname: ansible-roletest-log-management
    vmware_network_name: DATA-1
    vmware_datastore: Datastore
    vmware_datacenter: devel
    vmware_vcenter_address: 192.168.100.30
    memory: 4096
    cpu: 2
    disk_size: 20
    os_template: template_centos7_v01
    esxi_hostname: 192.168.100.20

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      ansible-roletest-log-management:
        lm_server_roles:
          - logstash
          - elasticsearch
          - kibana
          - rsyslog
          - auditbeat
          - filebeat

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
