---
dependency:
  name: galaxy
  options:
    ignore-certs: true
driver:
  name: delegated
  options:
    managed: true
lint:
  name: yamllint
platforms:
  - name: ansible-roletest-log-management
    vmware_hostname: ansible-roletest-log-management
    vmware_network_name: DATA-1
    vmware_datastore: Datastore
    vmware_datacenter: devel
    vmware_vcenter_address: 192.168.100.30
    memory: 4096
    cpu: 2
    disk_size: 20
    os_template: template_centos7_v01
    esxi_hostname: 192.168.100.20

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_common_args: -F /tmp/ssh_config
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      ansible-roletest-log-management:
        parted_action: resize
        parted_device: /dev/sda
        parted_number: 2
        lvm_vgname: vg01
        lvm_lvname: root
        lvm_lvfilesystem: ext4
        lvm_lvmount: /
        lvm_lvsize: 18G
        lm_server_roles:
          - logstash
          - elasticsearch
          - kibana
          - rsyslog
          - auditbeat
          - filebeat
          - elastalert
          - cerebro
        lm_elasticsearch_jvm_opts:
          - { name: Xms, value: Xms1g }
          - { name: Xmx, value: Xmx1g }
        lm_elastalert_rules:
          - name: Nginx errors
            type: frequency
            index: logstash-*
            num_events: 50
            timeframe:
              minutes: 5
            buffer_time:
              minutes: 15
            filter:
              - term:
                  fields.logtype: nginx_access
              - range:
                  status:
                    from: 500
                    to: 600
              - query:
                  query_string:
                    query: "request: transferuj.php"
            alert:
              - email
            email:
              - jan.michalek@betsys.com
            alert_text_type: exclude_fields

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
