---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  tasks:
    - name: create machine
      include_tasks: vmware/create_machine.yml platform={{ item }}
      with_items: "{{ molecule_yml.platforms }}"
